In [1]:
import pandas as pd
df=pd.read_csv('d:\customer_shopping.csv')
df

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\LOQ\AppData\Local\Temp\ipykernel_4060\1615485986.py:2: SyntaxWarning: invalid escape sequence '\c'
  df=pd.read_csv('d:\customer_shopping.csv')

,Transaction ID,Customer ID,Purchase Date,Age,Gender,Location,Online/Offline,Online Store,Category,Item Purchased,...,Festival/Sale,Shipping Charge (₹),Delivery Speed,Delivery Time (Days),Subscription Status,Payment Method,Review Rating,Return Status,Previous Purchases,Frequency of Purchases
0,TXN507808,CUST102534,2023-01-01,51,Male,Chennai,Online,Flipkart,Clothing,Kurta,...,NaN,0,Same Day,1,Yes,Cash on Delivery,4,Not Returned,0,Fortnightly
1,TXN503830,CUST101256,2023-01-01,27,Female,Mumbai,Offline,NaN,Clothing,Shirt,...,NaN,0,NaN,0,No,UPI,5,Not Returned,0,Fortnightly
2,TXN501496,CUST100490,2023-01-01,57,Male,Hyderabad,Online,Flipkart,Clothing,Jacket,...,NaN,0,Standard,7,Yes,UPI,3,Not Returned,0,Rarely
3,TXN501538,CUST100500,2023-01-01,22,Female,Pune,Online,Myntra,Clothing,Kurta,...,NaN,0,Standard,6,Yes,Net Banking,4,Not Returned,0,Fortnightly
4,TXN504265,CUST101399,2023-01-01,30,Male,Visakhapatnam,Online,Myntra,Accessories,Cap,...,NaN,99,Express,2,No,Debit Card,4,Not Returned,0,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN509420,CUST102996,2024-12-31,30,Male,Bangalore,Online,Flipkart,Clothing,Trousers,...,End of Season Sale,199,Express,4,No,Debit Card,3,Not Returned,8,Fortnightly
9996,TXN500945,CUST100273,2024-12-31,58,Female,Kolkata,Online,Flipkart,Clothing,Saree,...,End of Season Sale,149,Express,4,No,UPI,5,Not Returned,1,Monthly
9997,TXN501737,CUST100566,2024-12-31,27,Female,Chennai,Online,Myntra,Clothing,Trousers,...,End of Season Sale,0,Standard,8,No,UPI,4,Not Returned,5,Weekly
9998,TXN506133,CUST102017,2024-12-31,48,Male,Bangalore,Online,Myntra,Footwear,Sandals,...,End of Season Sale,99,Standard,5,No,UPI,4,Not Returned,1,Monthly
9999,TXN501759,CUST100573,2024-12-31,20,Male,Pune,Online,Flipkart,Clothing,Hoodie,...,End of Season Sale,0,Standard,5,No,Debit Card,4,Not Returned,1,Monthly

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction ID          10000 non-null  object
 1   Customer ID             10000 non-null  object
 2   Purchase Date           10000 non-null  object
 3   Age                     10000 non-null  int64
 4   Gender                  10000 non-null  object
 5   Location                10000 non-null  object
 6   Online/Offline          10000 non-null  object
 7   Online Store            7751 non-null   object
 8   Category                10000 non-null  object
 9   Item Purchased          10000 non-null  object
 10  Brand                   10000 non-null  object
 11  Color                   10000 non-null  object
 12  Size                    8965 non-null   object
 13  Quantity                10000 non-null  int64
 14  Purchase Amount (₹)     10000 non-null  int64
 15  Discount (%)            10000 non-null  int64
 16  Festival/Sale           3212 non-null   object
 17  Shipping Charge (₹)     10000 non-null  int64
 18  Delivery Speed          7751 non-null   object
 19  Delivery Time (Days)    10000 non-null  int64
 20  Subscription Status     10000 non-null  object
 21  Payment Method          10000 non-null  object
 22  Review Rating           10000 non-null  int64
 23  Return Status           10000 non-null  object
 24  Previous Purchases      10000 non-null  int64
 25  Frequency of Purchases  10000 non-null  object
dtypes: int64(8), object(18)
memory usage: 2.0+ MB

In [7]:
print(df.isnull().sum())

Transaction ID               0
Customer ID                  0
Purchase Date                0
Age                          0
Gender                       0
Location                     0
Online/Offline               0
Online Store              2249
Category                     0
Item Purchased               0
Brand                        0
Color                        0
Size                         0
Quantity                     0
Purchase Amount (₹)          0
Discount (%)                 0
Festival/Sale             6788
Shipping Charge (₹)          0
Delivery Speed            2249
Delivery Time (Days)         0
Subscription Status          0
Payment Method               0
Review Rating                0
Return Status                0
Previous Purchases           0
Frequency of Purchases       0
dtype: int64

In [6]:
df['Size']=df['Size'].fillna('Standard')
df['Size'].isnull().sum()

np.int64(0)

In [8]:
df['Delivery Speed']=df['Delivery Speed'].fillna('Standard')

In [9]:
df['Festival/Sale']=df['Festival/Sale'].fillna(0)
df['Online Store']=df['Online Store'].fillna(0)

In [10]:
df.isnull().sum()

Transaction ID            0
Customer ID               0
Purchase Date             0
Age                       0
Gender                    0
Location                  0
Online/Offline            0
Online Store              0
Category                  0
Item Purchased            0
Brand                     0
Color                     0
Size                      0
Quantity                  0
Purchase Amount (₹)       0
Discount (%)              0
Festival/Sale             0
Shipping Charge (₹)       0
Delivery Speed            0
Delivery Time (Days)      0
Subscription Status       0
Payment Method            0
Review Rating             0
Return Status             0
Previous Purchases        0
Frequency of Purchases    0
dtype: int64

In [11]:
df.describe()

,Age,Quantity,Purchase Amount (₹),Discount (%),Shipping Charge (₹),Delivery Time (Days),Review Rating,Previous Purchases
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,38.278100,1.425100,1889.882000,32.916300,41.49210,3.703600,3.874900,3.211400
std,12.133041,0.761346,2102.301836,21.440617,64.30923,2.726223,0.912871,3.951313
min,18.000000,1.000000,67.000000,0.000000,0.00000,0.000000,1.000000,0.000000
25%,28.000000,1.000000,600.000000,12.000000,0.00000,1.000000,3.000000,0.000000
50%,38.000000,1.000000,1207.000000,33.000000,0.00000,4.000000,4.000000,2.000000
75%,49.000000,2.000000,2376.000000,52.000000,79.00000,6.000000,5.000000,4.000000
max,59.000000,4.000000,22306.000000,70.000000,199.00000,8.000000,5.000000,28.000000

In [15]:
top_category=df.groupby('Category')['Purchase Amount (₹)'].sum()
display(top_category)

Category
Accessories    2635126
Clothing       8361260
Footwear       7902434
Name: Purchase Amount (₹), dtype: int64

In [17]:
top_category=df.groupby('Category')['Purchase Amount (₹)'].agg(
    total_revenue='sum',
    avg_purchase='mean',
    transaction_count='count'
).sort_values(by='total_revenue')
display(top_category)

             total_revenue  avg_purchase  transaction_count
Category
Accessories        2635126   1220.530801               2159
Footwear           7902434   2784.508104               2838
Clothing           8361260   1671.249250               5003

In [18]:
#Age filter
df['age_group']=pd.cut(
    df['Age'],
    bins=[0,25,40,60,100],
    labels=['18-25', '26-40', '41-60', '60+']
)

age_analysis=df.groupby('age_group', observed=False)['Purchase Amount (₹)'].agg(
    total_spend='sum',
    avg_spent='mean'
)
display(age_analysis)

           total_spend    avg_spent
age_group
18-25          3821854  1916.677031
26-40          6971447  1918.394882
41-60          8105519  1853.961345
60+                  0          NaN

In [20]:
correlatiom_matrix=df[['Discount (%)', 'Purchase Amount (₹)', 'Quantity']].corr()
display(correlatiom_matrix)

                     Discount (%)  Purchase Amount (₹)  Quantity
Discount (%)             1.000000             0.164880 -0.001037
Purchase Amount (₹)      0.164880             1.000000  0.504029
Quantity                -0.001037             0.504029  1.000000

In [21]:
payment_analysis=df.groupby('Payment Method')['Purchase Amount (₹)'].agg(
    total_revenue='sum',
    transaction_count='count'
).sort_values(by='total_revenue', ascending=False)
display(payment_analysis)

                  total_revenue  transaction_count
Payment Method
UPI                     8248679               4411
Credit Card             3510178               1582
Debit Card              2836286               1533
Cash on Delivery        1325528                987
Net Banking             1097679                586
EMI                      979976                430
Wallet                   900494                471